version: "3"
services:
  db:
    container_name: mysql-80
    image: mysql:8.4
    platform: linux/amd64
    ports:
      -  "8036:3306" #port ouvert côte machine à gauche et port ouvert coté docker à droite qui est par defaut
    restart: always
    environment:
      MYSQL_DATABASE: app_db
      #MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_PASSWORD: ort
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./dbdata:/var/lib/mysql # /var/lib/mysql ce fichier mysql sur Docker sera envoyer sur un fichier qui vas ce crée dans l'arboressance il s'appelle ./dbdata
  phpmyadmin:
    container_name: pma-80
    image: phpmyadmin/phpmyadmin
    ports:
      - "8082:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 1G
      MEMORY_LIMIT: 512M
      MAX_EXECUTION_TIME: 0
    restart: always
    links:
      - db
#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - "8081:8080"
#    environment:
#      ADMINER_DEFAULT_SERVER: db
#      ADMINER_DESIGN: "lucas-sandery"
#    links:
#      - db

volumes:
  dbdata:
